### PR TITLE
GTK 3.20 :: Add style classes to nemo's window, desktop window, and sidebar

### PR DESCRIPTION
**Pull request by lots0logs**
@clefebvre @mtwebster Replaces #1131

### CODE REVIEW

**Comment by lots0logs** [comment]
@clefebvre @mtwebster What's the status on this?

**Comment by JosephMcc** [comment]
I can't answer your question about the status. I do know the addition of the "places-sidebar" style class in unneeded.

**Comment by lots0logs** [comment]
@JosephMcc That's your opinion. IMO as someone who currently co-maintains a popular gtk theme, its needed. Also, there's is absolutely zero cost (downside/cons) associated with the inclusion of the style class so why not make the lives of theme developer's a little bit easier? Just my two cents.

**Comment by JosephMcc** [comment]
I'm familiar with gtk theming. How would it add anything different than using ".nemo-window .sidebar" besides having another style class doing the same thing?

**Comment by lots0logs** [comment]
`.sidebar` is not the same node as `.places-sidebar`. Obviously there are other ways to target that node. I was simply trying to point out that what you said was an opinion even though you were very *matter-of-fact* in the way that you said it.

**Comment by JosephMcc** [comment]
I understand and admit I'm not familiar with all the theming changes in 3.20. If you want a class to specifically target the nemo sidebar I would prefer something like `nemo-sidebar` since it is specific and won't show up being used by something else. I'm not a fan of the idea of adding something with such a general name when it's already possible to target it with your addition of `nemo-window`.

**Comment by clefebvre** [comment]
Hi guys.

@lots0logs can you prefix the sidebar class with "nemo" to make it specific or remove it altogether?

Other than that this is ready to merge.

**Comment by lots0logs** [comment]
@clefebvre Done :smile:

**Comment by clefebvre** [comment]
Thanks :)

**Pull request merged**
