### PR TITLE
Add Cinnamon panel shortcuts (trash, computer, etc.) to the launcher

### PR DESCRIPTION
**Pull request by germanfr**
**Screenshot:** 
screenshot from 2016-11-05 17-27-27

(This will need translations for the words _Home_, _Trash_ and _Computer_)

### CODE REVIEW

**Comment by clefebvre** [comment]
Good idea.

I had to reimplement it differently though as I wanted the translations in there.

The desktop file is now generated ala Mint (i.e. via mint-common).

https://github.com/linuxmint/nemo/commit/ba5ba23b1071e851e00623bf9824903d7a86fc75

**Comment by germanfr** [comment]
Hi @clefebvre. I've just updated Nemo and there's a bug with the generated desktop file. For some reason the names are changed to "Nemo". Here's a part of the desktop file installed on my system.
```desktop
[Desktop Action open-home]
Name=Nemo
Name[af]=Nemo
Name[am]=Nemo
Name[ar]=Nemo
Name[be]=Nemo
Name[be@latin]=Nemo
Name[be_BY]=Nemo
...
```

screenshot from 2017-05-19 18-47-12

**Comment by JosephMcc** [comment]
Are you running Arch? Talking to another of the devs who runs it, this is an issue with the Arch packaging. 

> Yes the problem is Arch 
In the Nemo package build they are seding and breaking the desktop 
There is a SED to rename files to Nemo and it changes the desktop file actions to Nemo as well

**Comment by itzexor** [comment]
@germanfr If you are on arch, it will probably be resolved soon. I have opened a bug report here https://bugs.archlinux.org/task/54119

If you're on another distro they might be doing the same type of rename, so check the packaging files.

**Comment by germanfr** [comment]
Yes, I'm on Arch (kind of). I'm on Manjaro. Yes they are actually renaming "Files" to "Nemo". So I'll just wait, it's not an issue for me anyway :)

**Pull request closed without merging**
