### PR TITLE
Fix desktop redraws in GTK 3.21.3 and later

### LINKED ISSUE #1231: gtk-3.21.4 no desktop redraws or bg changes until restart
Caja has the same issue

https://github.com/mate-desktop/caja/issues/575

I have managed to fix the redraw issue with this patch

[canvas-container.patch.txt](https://github.com/linuxmint/nemo/files/376660/canvas-container.patch.txt)

taken from

https://git.gnome.org/browse/nautilus/commit/?h=gnome-3-8&id=6d6bf1e7c6049b4bd300ae1d90833a8b5fcf30c4

There is a side affect, the background is rendered grey.

screenshot from 2016-07-21 19-13-07

### PR DESCRIPTION
**Pull request by lukefromdc**
GTK 3.21.3 and later broke desktop redrawing except in Nautilus. The commit that made the difference between it working and not working was traced to 
https://github.com/GNOME/nautilus/commit/6d6bf1e7c6049b4bd300ae1d90833a8b5fcf30c4
canvas-container: don't force native window for the desktop canvas 
shortly before Nautilus 3.7.21 came out. To make this work on Nemo also required forcing the scrolledwindow of nemo-desktop-icon-view transparent with a cssprovider, as otherwise it would put a white background on the desktop. Works, running it right now as I post this.

Fixes #1231

### CODE REVIEW

**Comment by itzexor** [comment]
Tagging https://github.com/mate-desktop/caja/issues/575 and https://github.com/linuxmint/nemo/issues/1231 so that those people can test this if they want.

**Comment by mtwebster** [comment]
Hi,

Can you try putting the css in this file: https://github.com/linuxmint/nemo/blob/master/src/nemo-style-application.css - it gets loaded during nemo startup, and would be cleaner than how it is here.

I'll try to test this weekend as well.  Thanks

**Comment by lukefromdc** [comment]
I just tried that, it only worked in Adwaita because all other themes I have override
the css file and put their background on the desktop. With the cssprovider themes
are overridden.

**Comment by leigh123linux** [comment]
@lukefromdc 

this works for some themes, the patch still needs some work

[canvas-container.patch.txt](https://github.com/linuxmint/nemo/files/379049/canvas-container.patch.txt)

**Comment by lukefromdc** [comment]
You found a problem the GNOME developers had a lot of trouble with in later Nautilus work: both the notebook and both paned widgets pick up default background colors in many but not all themes. Only my own theme and Adwaita work either with my original PR or with your patch version(which also works).  The offending widgets are both paned widgets and the notebook. The notebook can be turned transparent in nemo-style-application.css but both paned widgets get it overridden by the theme and show the theme background color. I could fix that but would be using gtk_widget_set_name or adding a style class to them. A quick test with the set_css_name code gave a build failure after I used it wrong in some way.

**Comment by leigh123linux** [comment]
I've altered the css in the patch to try and address the themes issues, I've tested with mate-themes and arc themes and they seem to work.


[canvas-container.patch.txt](https://github.com/linuxmint/nemo/files/379531/canvas-container.patch.txt)

**Comment by lukefromdc** [comment]
I'll try this later today (Monday) I was out of town all day today

**Comment by lukefromdc** [comment]
I just tested your latest patch, all the MATE themes still drew their background colors on the desktop. Adwaita, Raleigh, and my own UbuntuStudio_Legacy theme all worked. Troublesome widgets were the notebook and paned widgets.  Editing the css file got it to work in every theme I have, though I found out the hard way that I had to run "make clean" between every test or the gresource based on this file would not be regenerated (ugh). The patch below resulted:

```
--- /home/luke/Desktop/nemo-style-application.css	2016-07-26 00:16:35.497198233 -0400
+++ /home/luke/Desktop/nemo-style-application.css_FIXED	2016-07-26 00:54:24.208289398 -0400
@@ -1,7 +1,10 @@
 /* Desktop text stuff */
 
 .nemo-desktop-icon-view,
-.nemo-desktop-icon-view .view {
+.nemo-desktop-icon-view .view,
+.nemo-window-pane,
+.nemo-desktop-window paned,
+.nemo-desktop-window notebook{
     background-color: transparent;
 }
```

**Comment by lukefromdc** [comment]
Closing in favor of https://github.com/linuxmint/nemo/pull/1235 which uses a better approach to the same job and is what I now use myself

**Comment by lukefromdc** [comment]
Closing in favor of https://github.com/linuxmint/nemo/pull/1235 which uses a better approach to the same job and is what I now use myself

**Pull request closed without merging**
