### PR TITLE
Fixes issue with desktop sort not saving

### LINKED ISSUE #2239: Desktop item sort mode is not saved
```
 * Cinnamon version = 4.0.9
 * Distribution = Linux Mint 19.1
 * Graphics hardware = ACER TravelMate integrated graphics
 * 64 bit
 ```

**Issue**
When customizing the current monitor layout, if a sorting mode other than "name" is selected for items, that value is not maintained, because if you reopen the same menu, the value is always reset to "name"

**Steps to reproduce**
1. Right click on desktop
1. Choose "Customize"
1. Change "Sort items by" to "Size", "Type" or "Date"
1. Close window
1. Right click on desktop
1. Choose "Customize"
1. "Sort items by" is reset to "Name"

**Expected behaviour**
"Sort items by" should remember the previous value

### PR DESCRIPTION
**Pull request by icarter09**
This PR resolves #2239

### CODE REVIEW

**Comment by mtwebster** [comment]
Can you add more info to the commit message?

**Comment by icarter09** [comment]
Updated the commit message.

**Comment by mtwebster** [comment]
Can you put the issue # also in the commit message?

*runs away...*

**Comment by icarter09** [comment]
Commit message updated to contain the issue #.

**Pull request merged**
