### PR TITLE
Debian packaging: small fixes

### PR DESCRIPTION
**Pull request by darealshinji**
Fixes:
```
dpkg-gencontrol: warning: Depends field of package libnemo-extension-dev: unknown substitution variable ${shlibs:Depends}
dpkg-gencontrol: warning: Depends field of package gir1.2-nemo-3.0: unknown substitution variable ${gir:Depends}
dpkg-gencontrol: warning: Depends field of package gir1.2-nemo-3.0: unknown substitution variable ${shlibs:Depends}

W: nemo source: ancient-standards-version 3.9.2 (current is 3.9.5)
E: nemo source: not-binnmuable-any-depends-all nemo -> nemo-data
E: nemo-data: python-script-but-no-python-dep usr/share/nemo/actions/myaction.py
```

### CODE REVIEW

**Comment by clefebvre** [comment]
What is the consequence of https://github.com/darealshinji/nemo/commit/422f4b2b8d0b3434b8a3e7a211205da07f3bd7b5 ?

**Comment by darealshinji** [comment]
@clefebvre If makes use of the `${gir:Depends}` substitution variable and get's rid of this warning that otherwise appears during the build:
 `dpkg-gencontrol: warning: Depends field of package gir1.2-nemo-3.0: unknown substitution variable ${gir:Depends}`

**Comment by clefebvre** [comment]
E: Package 'python2' has no installation candidate (Linux Mint 17.x)

**Comment by darealshinji** [comment]
Changed it to python2.7

**Pull request merged**
