### PR TITLE
Add native exfat renaming support

### PR DESCRIPTION
**Pull request by leigh123linux**
Fixes:  https://github.com/linuxmint/nemo/issues/2708

### CODE REVIEW

**Comment by eyalroz** [comment]
So what exactly changes with this PR merged?

**Comment by leigh123linux** [comment]
@eyalroz  It adds support for kernel exfat.
Microsoft files systems can't handle some characters, see

https://github.com/linuxmint/nemo/blob/def5cf21c744e7926de8828679ed101f3940d885/libnemo-private/nemo-file-operations.c#L3393

**Comment by eyalroz** [comment]
@eyalroz :  I know, I filed #2708 ; I mean, in what sense is support added? What happens now when you copy to/from exfat and some characters are unsupported?

**Comment by mtwebster** [comment]
Any invalid characters are replaced with an underscore `_`.

**Comment by eyalroz** [comment]
@mtwebster : Ah, ok, now I get it. Would have spared you the question if you would have been this verbose in the original PR description :-P

**Pull request merged**
