### PR TITLE
[Branch] Nemo merge with Nautilus 3.14.3

### PR DESCRIPTION
**Pull request by daschuer**
This is a systematic merge branch crawling up the Nautilus history to 3.14.3 
It is the successor of https://github.com/linuxmint/nemo/pull/872.

You can find binary builds for Ubuntu here:
For plain Ubuntu Trusty setups with unity support:
https://launchpad.net/~daschuer/+archive/ubuntu/nemo-merge
And for Ubuntu Trusty with Cinnamon installed:
https://launchpad.net/~daschuer/+archive/ubuntu/nemo-nautilus-merge-cinnamon

Please note: 
GitHub hides details from the commit history. To get an impression what this branch is use "gitk". 

New Features: 
* Port to be a DBusActivatable application
* Fix problems with fast group/owner changes
* Other bugfixes

Nautilus 3.12 Features in https://github.com/linuxmint/nemo/pull/872: 
* Fix arrow direction in connect server dialog for RTL (Yosef Or Boczko)
* Sync the GTK+ 3.12 setting for 'sort-directories-first' (Matthias Clasen)
* Only show one button for mixed Video CD/Video DVD media
* Add a force-desktop action to NautilusApplication (Ray Strode)
* Add film strip in nautilus rather than in totem (Bastien Nocera)
* Fix overlapping filenames on hover in canvas view (Manuel Bachmann)
* Use search bar style for the query editor (William Jon McCann)
* Improve tab labels (William Jon McCann)

Nautilus 3.10 Features in https://github.com/linuxmint/nemo/pull/864:
* Use new gtk_drag_begin_full API (Jasper St. Pierre)
* Don't filter out NoDisplay applications from "Open With..."
* Fix crash while dragging an expander in list view
* Don't use some deprecated GtkStock 
* Use more friendly strings in the Location column in
  List view (Garret Regier)
* Add Access Date column in Recent (Garret Regier)
* Add Location column by default in search views (Garret Reiger)
* Shade rubberbands on the desktop using the wallpaper color (Ted Gould)
* Enter location bar upon entering "~" (Garrett Regier)
* Use Shift+Ctrl+Z, not Ctrl+Y, for Redo (Adam Dingle)

Nautilus 3.8 Features in https://github.com/linuxmint/nemo/pull/812:
* Don't follow symbolic links when searching recursively
* Ensure target directories exist when restoring trash contents (3.8)
* Export an OpenLocations property over DBus (Marco Trevisan)
* Use an ARGB window for the desktop (Matthias Clasen)
* Stop drawing the desktop background
* Add a "Connect to Server" item in the Network section of the sidebar
* Add a "Format..." item in volume context menus in the sidebar
* Use a better position for navigation button popup menus
* Support a --select commandline option to force selection of the passed-in URI
* Modernize build infrastructure (Javier Jardon)
* Update search provider to org.gnome.Shell.SearchProvider2 interface
* Rely on GIO to parse ".hidden" files
* Consistently use unicode ellipsis instead of three periods (Jeremy Bicha)
* Use a different label for removing a file from "Recent" (Paolo Borelli)
* Share the "show hidden" GSetting option with the GTK+ file chooser (Timothy Arceri)

Nautilus 3.6 Features in https://github.com/linuxmint/nemo/pull/565:
* Search provider: Tracker / Simple / Model 
* Search results are updated during search. 
* Use a ranking algorithm for search results
* Shell search results provider
* Fresh connect to server dialog 
* :ok: new search query dialog 
* Add cluebars for Templates and Scripts special directories
* Add a notification while ejecting volumes
* :ok: Add a recent files place 
* Location bar with Icon 
* Don't pack multiple x-content bars in the view and added icons 
* Add a way to create a new directory for selection

For a complete changelog see https://github.com/daschuer/nemo/blob/nemo_314_merge_nemo_base/NEWS

------

Whats the user of this? 

I use it on my productive systems and I am very pleased with it. :-)
If you decide, to merge a single Nautilus feature, it is much easier to start from this this branch, because it merges to the master without conflicts.

### CODE REVIEW

**Comment by belandsoft** [comment]
I use your compiled (.deb) version of nemo with nautilus 3.14.3 patches integration, but i suffer of this bug https://github.com/linuxmint/nemo/issues/1010 that was fixed on nemo on 17 Dec 2015, so please can you update your ubuntu ppa to the latest version of nemo, thanks!

**Comment by daschuer** [comment]
Hi @belandsoft:

I am very happy to read that there is an other user of this branch except me :-D
So all the hard work was not just for me. 

The ppa is updated. You are welcome to test and comment more ...
Thank you.

**Comment by clefebvre** [comment]
Hi @daschuer. The work you're doing on these branches is pretty cool and I think it helps in some cases, but it could be done on your github repo all the same and mtwebster and other devs can cherry-pick and merge from there as well. Your repo can be used to test and to produce PPA debs just as well as these branches.

Also, if there's a particular feature which should be imported from nautilus into nemo, after we test it in nautilus or in your branch/repo, we need to look at it in isolation, outside the context of a general rebase/import from nautilus.

With that in mind, and mostly for practical reasons (merging PRs is also a number game), I'll close these PRs now and suggest these branches continue over on https://github.com/daschuer/nemo.

**Comment by daschuer** [comment]
@clefebvre: It would be great, If you can still reference this branch somehow that people find it. 
I have already to deal with situations where the same bugs are fixed in Nemo and Nautilus, but in a slightly different way. It would be nice if those fixes where taken from this branch instead of adopting this new. 
Is it possible to make this a https://github.com/linuxmint/nemo branch with write access for me?

**Comment by daschuer** [comment]
The original branch is now up to date with Nemo 3.2 and latest master. 
I would be happy about any feedback!

**Comment by gerardoglz** [comment]
Great work @daschuer. One question, where do I report bugs of your nemo branch? launchpad.net/~daschuer ?

**Comment by daschuer** [comment]
Cool, You found this branch! Thank you for testing. 
I have just opened "issues" section on GitHub:  
https://github.com/daschuer/nemo/issues

**Pull request closed without merging**
