### PR TITLE
 Middle click on parent/previous/next folder

### PR DESCRIPTION
**Pull request by denis-golubev**
Adjust the event handler of the toolbar buttons "Back", "Forward" and "Up" to handle middle clicks.

The following changes were performed in the file `nemo-navigation-action.c`:
 - `tool_button_press_cb` has been extended to call the new function `new_tab_action`, if the button id is `2` and the event type is "pressed" (otherwise, double clicking with the middle mouse button causes `new_tab_action` to be called three times).
- `new_tab_action`: Similar to `show_menu`, the behavior is dependent on the navigation direction. This function reuses already existing functions from existing event handlers. To open new tabs, the `NEMO_WINDOW_OPEN_FLAG_NEW_TAB` flag is used when calling the aforementioned methods.

Proposed implementation of the feature request #1062.

P.S. This is my first pull request for Nemo. I would be happy about comments on it, e.g. about style (code, commit message) and about amount of documentation (too little / too detailed).

### CODE REVIEW

**Comment by clefebvre** [comment]
That's pretty cool. If we follow on the tracks of FF here, could we also support CTRL+Click to do the same thing?

**Comment by clefebvre** [comment]
Not sure we need g_assert_not_reached (); in the default case.

**Comment by denis-golubev** [comment]
Taking a quick look into the documentation, the event structure has modifier states. So it should be possible by just extending the if-condition. I'm going to try it tomorrow.

Initially, I wanted to keep all the unsupported cases out of the switch and just return FALSE in the default case, but the function `show_menu` in the same file did it that way and I tried to imitate the structure. Should I change it?

**Comment by clefebvre** [comment]
I think so, we shouldn't terminate the application or consider an error when it doesn't matter. In fact I wouldn't even enumerate all cases here... I'd enumerate the ones to react on and simply return FALSE in default.

**Comment by denis-golubev** [comment]
Should I create a new pull request for the requested changes of the `new_tab_action` function? I have also added the CTRL-Click behavior.

**Comment by clefebvre** [comment]
hi @denis-golubev, yes please.

**Pull request merged**
