### PR TITLE
Fix issue 2157 (Support the exec-arg gsettings for the open in terminal command)

### PR DESCRIPTION
**Pull request by BeatLink**
This is a recreation of https://github.com/linuxmint/nemo/commit/7ca7990c0c33fa4a4f19ba0f534f00f221acb480

### CODE REVIEW

**Comment by JosephMcc** [comment]
Thanks for the contribution but it would be nice to see the commit message actually say what this does. When someone is coming back to this in the future it is much more clear that way. This could be as simple as "support the exec-arg for the open in terminal command"

**Comment by BeatLink** [comment]
Fixed! (Though I had to force push the amended commit)

**Comment by clefebvre** [comment]
Why bring this commit back?

It was reverted and the justification for this is described at https://github.com/linuxmint/nemo/commit/d18a44c67c7385cae8d2ec40c8d625797e6a411e.

**Comment by BeatLink** [comment]
I already mentioned that guake cannot work without arguments

**Comment by clefebvre** [comment]
https://github.com/linuxmint/nemo/issues/2157

**Comment by BeatLink** [comment]
Yes that's the one

**Pull request closed without merging**
