### PR TITLE
[WIP] Nautilus Search1

### PR DESCRIPTION
**Pull request by daschuer**
This is the pilot pull request of a row of commit that merges the nautilus search features into Nemo. 

Since a with a huge merge, we will be not able to review an track the changes, we have discussed to do it in small working chunks. 
The final result with additional unrelated fixes can be tested here:  
https://github.com/linuxmint/nemo/pull/565

### CODE REVIEW

**Comment by daschuer** [comment]
Is this merge-able?  Any other comments?

**Comment by mtwebster** [comment]
I played with the 3.8 rebase a few weeks ago, the new search stood out for me - I'll try merging this in and running on top of master.  I need to make sure the rest of the devs agree on something this major though.  Thanks

**Comment by mtwebster** [comment]
Testing this a bit more - the 'up' toolbar button is enabled during a search, but doesn't actually do anything (only the back button works).

Also, if the search takes longer than a few seconds, the UI ends up freezing until the search results are completed.  Try starting a search, typing 't' (or any single letter) and then pause a moment.

**Comment by daschuer** [comment]
Thank you for testing. that is the fist PR, towards the whole search feature. 
The UP issue and the freezing issue will be fixed when we cawl up to the top. 
It is cause by the fact that the underlying search engine is almost unchanged compared to master. 
The up button does not work at master as well. 

How do the other developers think about it? 

Do you can effort the time to code review this PR? Maybe we can merge it step by step into an experimental branch and then finally merge it to master.

**Comment by daschuer** [comment]
This is again in a merge-able state. Any considerations how to continue?

**Comment by mtwebster** [comment]
I rebased and merged this:

https://github.com/linuxmint/nemo/commit/bf3608459f665e6e22fcd1989ac919d921910b0e
https://github.com/linuxmint/nemo/commit/4d50cffdcafc61d58ddf73437ae69bf0f408d523

I didn't want to mess up history by the merge commits.

Works well, and looks a lot nicer, a couple things I'd like to see:

- Have a default folder to keep bookmarked searches (`~/.local/share/nemo/searches` ?)
- Saving search from the file menu remains unchanged
- Dragging the location widget, or bookmarking a current search view, creates a saved search in that default folder, and bookmarks it.  Currently, I can drag-and-drop a new bookmark, and it works, but only for the current nemo session. (It's using x-nemo-search://0/, /1/, etc... which only corresponds to a made-up, in-memory folder)

**Comment by daschuer** [comment]
@mtwebster: Thank you for merging this! :-)

>  a couple things I'd like to see: ..

Good ideas! Do you know if Nautilus has something similar in it's recent version? 

Next, I will prepare a PR for the subsequent seach commits from https://github.com/linuxmint/nemo/pull/872

**Pull request closed without merging**
