### PR TITLE
Add control to context menu to toggle simple/complex menu

### PR DESCRIPTION
**Pull request by mtwebster**
screenshot-monitor-2015-10-19-081146

not ready... just concept - need to:

- always show all entries in pulldown menus
- only show widget in selection menu (not background click)
- small GC issue

### CODE REVIEW

**Comment by clefebvre** [comment]
Nice! 

Couple of comments re-visuals:

- Have a different icon for collapse/expand, maybe just a little + or - sign
- Add a tooltip to it if possible

**Comment by mtwebster** [comment]
Works better now, most issues fixed, just need a tooltip and fix the menu position when re-showing back to the original popup location.  Maybe better icons, not crazy about the gtk-remove icon.

**Comment by mtwebster** [comment]
plus
minus

**Comment by clefebvre** [comment]
Looks nice, icons are way too big though.

**Comment by clefebvre** [comment]
This can go in, it works very well. If we merge it, it has to be before the Mint RC and it needs the following:

- The icons should be smaller.
- Tooltips should be more explicit "Show more options", "Show less options".

And then, not needed, but would be nice at some stage:

- The icons should be within a button which border is revealed on hover. Similar to the color buttons in the folder color extension. This would make it look better, and also allow the clickable zone to be as big as it is now, while making the icon smaller.

**Pull request merged**
