### PR TITLE
Silence a bunch of allocation warnings when using GTK 3.20

### LINKED ISSUE #1153: Allocating size to GtkButton without calling  gtk_widget_get_preferred_width/height()
After updating to nemo 2.8.7. I get the following error in my .xsession-errors

    (nemo:16703): Gtk-WARNING **: Allocating size to GtkButton 0xf7cdb0 without calling 
    gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

When the window is inactive no errors appear, but every time I click on the window or do any other action like changing the folder 8kB of errors are produced. In a normal workflow .xsession-errors increases to megabytes  fast.

### PR DESCRIPTION
**Pull request by itzexor**
A few still remain, but this should make logs readable again.

Edit: I haven't tracked down the NemoWindow warnings yet and the NemoWindowPane warnings are fixed by this gtk commit https://github.com/GNOME/gtk/commit/ddcf47026dbbe58dca3b34c7bb1ec63bb50a861

Fixes #1153

### CODE REVIEW

**Comment by brownsr** [comment]
This all seemed well behaved when I tried it on LM18.  I did get this additional entry in .xsession-errors compared to beforehand, which may be coincidental.  Could not tell you how it was triggered, as I was just doing an unstructured run through of nemo as a whole.
(nemo:1665): Gtk-CRITICAL **: gtk_widget_draw: assertion '!widget->priv->alloc_needed' failed

**Comment by leigh123linux** [comment]
@itzexor  Thank you for fixing the log spam, down from 1Mb to 2,2kb per day.

@brownsr 

I don't see that warning here (fedora 24 gtk-3.20)

```
SELinux Troubleshooter: Applet requires SELinux be enabled to run.
Failed to play sound: Sound disabled
sys:1: PyGIWarning: Nemo was imported without specifying a version first. Use gi.require_version('Nemo', '3.0') before import to ensure that the right version gets loaded.
Cjs-Message: JS LOG: About to start Cinnamon

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed

(nemo:722): Gdk-CRITICAL **: gdk_window_get_origin: assertion 'GDK_IS_WINDOW (window)' failed
St-Message: cogl npot texture sizes SUPPORTED
Cjs-Message: JS LOG: Cinnamon started at Fri Jun 17 2016 11:05:12 GMT+0100 (BST)
Cjs-Message: JS LOG: network applet: Cannot find connection for active (or connection cannot be read)
openGL version 3.1 detected (GL3 Cogl Driver)
Cjs-Message: JS LOG: Invalid network device type, is 14
Cjs-Message: JS LOG: network applet: Found connection for active

(nemo:722): Gtk-WARNING **: Allocating size to NemoWindowPane 0x55e75b24fd60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
Window manager warning: Log level 16: STACK_OP_RAISE_ABOVE: sibling window 0x16000f8 not in stack
Window manager warning: Log level 16: STACK_OP_LOWER_BELOW: sibling window 0x16000f8 not in stack
```

**Comment by itzexor** [comment]
@brownsr I'll have to double check to make sure, but I was assuming that was already there. The conditions that make it happen are described here: https://github.com/linuxmint/nemo/pull/838

**Comment by brownsr** [comment]
@itzexor Yes, that error I found was for the other reason you tracked down, nothing to do with your change.  I've put in a PR to fix it.

**Comment by zosy** [comment]
same issue 
get tons of errors bellow

(nemo:32258): Gtk-WARNING **: Allocating size to GtkGrid 0x10ffb60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?
(nemo:32258): Gtk-WARNING **: Allocating size to GtkGrid 0x10ffb60 without calling gtk_widget_get_preferred_width/height(). How does the code know the size to allocate?

PRODUCE
1.open nemo and move or drag the nemo window.

ENV
1.arch_86x64
2.gtk3 3.20.9-1
3.nemo 3.0.6
4.Cinnamon 3.0.7

**Comment by itzexor** [comment]
@zosy this patch is not in nemo 3.0.6 there hasn't been a release yet since this

**Comment by itzexor** [comment]
if you want, you can get the PKGBUILD from arch build system and apply this patch
https://github.com/linuxmint/nemo/commit/481c589458d01ca61d99cce6a93d93470bd8c9a9.patch

**Comment by zosy** [comment]
@itzexor got it ,thanks:)

**Pull request merged**
