### PR TITLE
Option to open uri in tabs at startup

### PR DESCRIPTION
**Pull request by klemsgithub**
Hello,
This is a patch to allow the opening of multiples uri in tabs at startup thought the command line (usefull to launch a single window with multiples tabs from a script)
As in Caja in which i've already implemented this feature, i've added the -t or --tabs option to open the uri in tabs. Without this option the current behaviour remains (one window is opened per uri)

### CODE REVIEW

**Comment by klemsgithub** [comment]
@clefebvre i've make this feature using command line but in the feature request https://github.com/linuxmint/nemo/issues/1795 somebody told me it wasn't a good idea to do so...
It's up to you to decide if you are interested in this modification :)

**Comment by mtwebster** [comment]
Hi, seems to work fine, except for one issue - 

I know in your changes you continue to respect the --geometry option, but if you try to use it in conjunction with --tabs, and supply multiple locations, it fails `do_cmdline_sanity_checks` - thinking geometry will not work with multiple locations.  I don't see why it shouldn't be allowed, though, if we're using the tabs option.

The only other issues I wouldn't mind seeing are style/formatting - you've got a lot of mixed tabs and spaces being used, in new code we use spaces exclusively (though we avoid mass changes of surrounding code from tabs to spaces unless it's a smallish function... best judgement here).

Also, there are some places with no space between function name and open parentheses, and spaces between operators and operands (x > 5 preferred over x>5).  These aren't that big a deal though..

Thanks

**Comment by klemsgithub** [comment]
@mtwebster I've corrected indentation and format. 
So what should i do for the geometry option?

**Comment by mtwebster** [comment]
I meant that you can't provide window geometry (`--geometry`) *and* have use `--tabs` when you provide more than one uri/location.

Add something like this, it should fix it:
```
diff --git a/src/nemo-main-application.c b/src/nemo-main-application.c
index f32b0d0eb..c4d77ccd7 100644
--- a/src/nemo-main-application.c
+++ b/src/nemo-main-application.c
@@ -506,6 +506,7 @@ do_cmdline_sanity_checks (NemoMainApplication *self,
               gboolean perform_self_check,
               gboolean version,
               gboolean kill_shell,
+              gboolean open_in_tabs,
               gchar **remaining)
 {
     gboolean retval = FALSE;
@@ -523,6 +524,7 @@ do_cmdline_sanity_checks (NemoMainApplication *self,
     }
 
     if (self->priv->geometry != NULL &&
+        !open_in_tabs &&
         remaining != NULL && remaining[0] != NULL && remaining[1] != NULL) {
         g_printerr ("%s\n",
                 _("--geometry cannot be used with more than one URI."));
@@ -631,7 +633,7 @@ nemo_main_application_local_command_line (GApplication *application,
     }
 
 	if (!do_cmdline_sanity_checks (self, perform_self_check,
-				       version, kill_shell, remaining)) {
+				       version, kill_shell, open_in_tabs, remaining)) {
 		*exit_status = EXIT_FAILURE;
 		goto out;
 	}
```

Now, the geometry option doesn't actually seem to work currently, but that's another problem.

Thanks

**Comment by klemsgithub** [comment]
done.

**Comment by clefebvre** [comment]
Hi @klemsgithub , 

The indentation changes should not be part of this PR. I know you've been waiting a while for this to get in and it's a bit unfair to request changes that late. Let me know if you're not available and I'll clean this up myself.

**Comment by klemsgithub** [comment]
Hi,
I'm a bit lost and i don't understand what to do...
Should i perform a rollback on the indentation modifications?

**Comment by clefebvre** [comment]
hi @klemsgithub, do you have the indentation changes separate from the actual implementation changes locally? If so, just push without them. If not, checkout the files where the only changes are indentation changes, and cancel the indentation changes in the files still modified.

**Comment by clefebvre** [comment]
Clement, I just noticed another thing.. your email isn't set up within your git config (i.e. we don't see it in the commit history).

**Comment by klemsgithub** [comment]
Ok, i've corrected my git environment with an email.
I don't have any changes not pushed and i've checked all the files i have modified so far and i don't see files with just indentation modifications... Did you saw such a file?

**Comment by clefebvre** [comment]
Sorry, just checking again, you're right... they all have implementation changes.

**Comment by clefebvre** [comment]
@klemsgithub I'll clean it up from here using git show.

**Comment by klemsgithub** [comment]
ok :)

**Comment by clefebvre** [comment]
Ok, it's in https://github.com/linuxmint/nemo/commit/0d2040b56fc0d5ead1c1cbb7a25bf5e5e9fefd86.

I put your name as the committer but I didn't have your email so I left it empty.

If your IDE is fixing the indentation automatically when you save a file you should disable that option. We do fix indentation now and then, but we try to do that in dedicated PRs/commits, and when necessary (in order not to to touch the git file history too much, it makes it easy to git blame that way).

I also noticed a few trailing spaces :) Same thing, don't have them deleted by default for the whole file, but if you have the option in your IDE to have them highlighted, do. That way you can see if you're adding some trailing spaces in your new code and remove them before you commit.

Anyway, thanks for this PR. It's in 4.2.0 now and so it will be part of the next release.

**Pull request closed without merging**
